<?php
/**
 * trade_list.php
 * Unified Trade Universe v1.9.0 CANDIDATE — normalized KR/US/JP schema
 * PHP 7.4 return-only
 *
 * 변경:
 * - v1.8.5 인터페이스/contract 완전 보존
 * - 기존 366개 종목 및 enabled/disabled 상태 보존
 * - 구조적 성장/신규 유망 Universe 12종목 보강
 *   KR: 산일전기(062040), 일진전기(103590), 한화비전(489790)
 *   US: ARM, CRWV, GEV, ORCL, RTX, SNDK, VST
 *   JP: Kioxia Holdings(285A), Kyocera(6971)
 * - 종목 수 변경은 consumer가 trade_list.php enabled Universe를 동적으로 추종하는 것을 전제로 함
 *
 * 배포 파일명: trade_list_v190-CANDIDATE.php
 * 운영 파일명: trade_list.php
 */
declare(strict_types=1);

if (isset($_SERVER['SCRIPT_FILENAME']) && realpath((string)$_SERVER['SCRIPT_FILENAME']) === __FILE__) {
    http_response_code(404);
    exit;
}

return [
    'meta'=>[
        'schema'=>'trade_list_v1_8',
        'version'=>'1.9.0',
        'contract'=>'trade_universe_contract_v2',
        'total_count'=>378,
        'strategy_keys'=>['abc','dts','stc26','das'],
        'updated_at'=>'2026-09-03',
        'kr_count'=>211,
        'kr_enabled_count'=>184,
        'kr_disabled_count'=>27,
        'us_count'=>115,
        'enabled_count'=>351,
        'disabled_count'=>27,
        'jp_count'=>52,
        'exchange_codes'=>['KR'=>['KOSPI','KOSDAQ','ETF'],'US'=>['NASD','NYSE','AMEX'],'JP'=>['TKSE']],
        'currencies'=>['KR'=>'KRW','US'=>'USD','JP'=>'JPY'],
        'required_fields'=>['symbol','code','name','market','exchange','currency','asset_type','enabled'],
        'derived_fields'=>['risk_group','correlation_group','is_inverse','is_leveraged'],
        'security'=>['direct_web_access'=>'blocked','include_only'=>true],
    ],

    'kr'=>[
        ['symbol'=>'000120','code'=>'000120','name'=>'CJ대한통운','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'000150','code'=>'000150','name'=>'두산','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'000250','code'=>'000250','name'=>'삼천당제약','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'000270','code'=>'000270','name'=>'기아','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'000660','code'=>'000660','name'=>'SK하이닉스','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'000720','code'=>'000720','name'=>'현대건설','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'001040','code'=>'001040','name'=>'CJ','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'001430','code'=>'001430','name'=>'세아베스틸지주','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'001440','code'=>'001440','name'=>'대한전선','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'001450','code'=>'001450','name'=>'현대해상','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'001510','code'=>'001510','name'=>'SK증권','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>false],
        ['symbol'=>'001740','code'=>'001740','name'=>'SK네트웍스','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'002790','code'=>'002790','name'=>'아모레G','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'003380','code'=>'003380','name'=>'하림지주','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'003490','code'=>'003490','name'=>'대한항공','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'003530','code'=>'003530','name'=>'한화투자증권','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>false],
        ['symbol'=>'003540','code'=>'003540','name'=>'대신증권','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>false],
        ['symbol'=>'003550','code'=>'003550','name'=>'LG','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'003670','code'=>'003670','name'=>'포스코퓨처엠','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'004020','code'=>'004020','name'=>'현대제철','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'004170','code'=>'004170','name'=>'신세계','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'005300','code'=>'005300','name'=>'롯데칠성','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'005380','code'=>'005380','name'=>'현대차','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'005490','code'=>'005490','name'=>'POSCO홀딩스','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'005830','code'=>'005830','name'=>'DB손해보험','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'005850','code'=>'005850','name'=>'에스엘','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'005930','code'=>'005930','name'=>'삼성전자','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'005935','code'=>'005935','name'=>'삼성전자우','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>false],
        ['symbol'=>'005940','code'=>'005940','name'=>'NH투자증권','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>false],
        ['symbol'=>'006360','code'=>'006360','name'=>'GS건설','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'006400','code'=>'006400','name'=>'삼성SDI','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'006650','code'=>'006650','name'=>'대한유화','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'006800','code'=>'006800','name'=>'미래에셋증권','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'007660','code'=>'007660','name'=>'이수페타시스','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'009150','code'=>'009150','name'=>'삼성전기','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'009540','code'=>'009540','name'=>'HD한국조선해양','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'009830','code'=>'009830','name'=>'한화솔루션','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'010060','code'=>'010060','name'=>'OCI홀딩스','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'010120','code'=>'010120','name'=>'LS ELECTRIC','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'010130','code'=>'010130','name'=>'고려아연','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'010140','code'=>'010140','name'=>'삼성중공업','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'010820','code'=>'010820','name'=>'퍼스텍','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true], // SIS
        ['symbol'=>'010950','code'=>'010950','name'=>'S-Oil','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'011070','code'=>'011070','name'=>'LG이노텍','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'011170','code'=>'011170','name'=>'롯데케미칼','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'011200','code'=>'011200','name'=>'HMM','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'012330','code'=>'012330','name'=>'현대모비스','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'012450','code'=>'012450','name'=>'한화에어로스페이스','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'012750','code'=>'012750','name'=>'에스원','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'014680','code'=>'014680','name'=>'한솔케미칼','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'015760','code'=>'015760','name'=>'한국전력','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'016360','code'=>'016360','name'=>'삼성증권','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'017670','code'=>'017670','name'=>'SK텔레콤','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'018880','code'=>'018880','name'=>'한온시스템','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'020150','code'=>'020150','name'=>'롯데에너지머티리얼즈','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'023530','code'=>'023530','name'=>'롯데쇼핑','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'024110','code'=>'024110','name'=>'기업은행','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'024740','code'=>'024740','name'=>'한일단조','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true], // SIS
        ['symbol'=>'025540','code'=>'025540','name'=>'한국단자','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'028260','code'=>'028260','name'=>'삼성물산','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'028670','code'=>'028670','name'=>'팬오션','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'030200','code'=>'030200','name'=>'KT','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'030530','code'=>'030530','name'=>'원익홀딩스','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'032640','code'=>'032640','name'=>'LG유플러스','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'033640','code'=>'033640','name'=>'네패스','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'034020','code'=>'034020','name'=>'두산에너빌리티','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'034220','code'=>'034220','name'=>'LG디스플레이','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'034730','code'=>'034730','name'=>'SK','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'035250','code'=>'035250','name'=>'강원랜드','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'035420','code'=>'035420','name'=>'NAVER','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'035720','code'=>'035720','name'=>'카카오','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'035760','code'=>'035760','name'=>'CJ ENM','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'035900','code'=>'035900','name'=>'JYP Ent.','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'036460','code'=>'036460','name'=>'한국가스공사','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'036540','code'=>'036540','name'=>'SFA반도체','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'036930','code'=>'036930','name'=>'주성엔지니어링','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'038500','code'=>'038500','name'=>'삼표시멘트','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'039030','code'=>'039030','name'=>'이오테크닉스','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'039490','code'=>'039490','name'=>'키움증권','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'041190','code'=>'041190','name'=>'우리기술투자','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'041510','code'=>'041510','name'=>'에스엠','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'042660','code'=>'042660','name'=>'한화오션','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'042700','code'=>'042700','name'=>'한미반도체','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'044490','code'=>'044490','name'=>'태웅','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'046120','code'=>'046120','name'=>'오르비텍','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'046890','code'=>'046890','name'=>'서울반도체','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'047040','code'=>'047040','name'=>'대우건설','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'047810','code'=>'047810','name'=>'한국항공우주','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'051900','code'=>'051900','name'=>'LG생활건강','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'051910','code'=>'051910','name'=>'LG화학','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'052690','code'=>'052690','name'=>'한전기술','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'053800','code'=>'053800','name'=>'안랩','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'055550','code'=>'055550','name'=>'신한지주','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true], // SIS
        ['symbol'=>'056080','code'=>'056080','name'=>'유진로봇','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'058470','code'=>'058470','name'=>'리노공업','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'058610','code'=>'058610','name'=>'에스피지','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'060250','code'=>'060250','name'=>'NHN KCP','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'062040','code'=>'062040','name'=>'산일전기','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'064260','code'=>'064260','name'=>'다날','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'064350','code'=>'064350','name'=>'현대로템','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'064400','code'=>'064400','name'=>'LG씨엔에스','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'065450','code'=>'065450','name'=>'빅텍','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true], // SIS
        ['symbol'=>'066570','code'=>'066570','name'=>'LG전자','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'066970','code'=>'066970','name'=>'엘앤에프','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'068270','code'=>'068270','name'=>'셀트리온','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'068760','code'=>'068760','name'=>'셀트리온제약','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'069500','code'=>'069500','name'=>'KODEX 200','market'=>'KR','exchange'=>'ETF','currency'=>'KRW','asset_type'=>'ETF','enabled'=>true],
        ['symbol'=>'069960','code'=>'069960','name'=>'현대백화점','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'071050','code'=>'071050','name'=>'한국금융지주','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'078340','code'=>'078340','name'=>'컴투스','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'078930','code'=>'078930','name'=>'GS','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'079550','code'=>'079550','name'=>'LIG넥스원','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'080220','code'=>'080220','name'=>'제주반도체','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'083650','code'=>'083650','name'=>'비에이치아이','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'086520','code'=>'086520','name'=>'에코프로','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'086790','code'=>'086790','name'=>'하나금융지주','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'088350','code'=>'088350','name'=>'한화생명','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'089790','code'=>'089790','name'=>'제이티','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'089970','code'=>'089970','name'=>'브이엠','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'090360','code'=>'090360','name'=>'로보스타','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'090430','code'=>'090430','name'=>'아모레퍼시픽','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'090710','code'=>'090710','name'=>'휴림로봇','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'091700','code'=>'091700','name'=>'파트론','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'095340','code'=>'095340','name'=>'ISC','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'095660','code'=>'095660','name'=>'네오위즈','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'095700','code'=>'095700','name'=>'제넥신','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'096530','code'=>'096530','name'=>'씨젠','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'096770','code'=>'096770','name'=>'SK이노베이션','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'097950','code'=>'097950','name'=>'CJ제일제당','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'099320','code'=>'099320','name'=>'쎄트렉아이','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'100790','code'=>'100790','name'=>'미래에셋벤처투자','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'101490','code'=>'101490','name'=>'에스앤에스텍','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'102110','code'=>'102110','name'=>'TIGER 200','market'=>'KR','exchange'=>'ETF','currency'=>'KRW','asset_type'=>'ETF','enabled'=>false],
        ['symbol'=>'103590','code'=>'103590','name'=>'일진전기','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'105560','code'=>'105560','name'=>'KB금융','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'108490','code'=>'108490','name'=>'로보티즈','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'112040','code'=>'112040','name'=>'위메이드','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'112610','code'=>'112610','name'=>'씨에스윈드','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'114800','code'=>'114800','name'=>'KODEX 인버스','market'=>'KR','exchange'=>'ETF','currency'=>'KRW','asset_type'=>'ETF','enabled'=>false],
        ['symbol'=>'120110','code'=>'120110','name'=>'코오롱인더','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'122630','code'=>'122630','name'=>'KODEX 레버리지','market'=>'KR','exchange'=>'ETF','currency'=>'KRW','asset_type'=>'ETF','enabled'=>false],
        ['symbol'=>'122870','code'=>'122870','name'=>'와이지엔터테인먼트','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'124500','code'=>'124500','name'=>'아이티센글로벌','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'130660','code'=>'130660','name'=>'한전산업','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'133690','code'=>'133690','name'=>'TIGER 미국나스닥100','market'=>'KR','exchange'=>'ETF','currency'=>'KRW','asset_type'=>'ETF','enabled'=>false],
        ['symbol'=>'138040','code'=>'138040','name'=>'메리츠금융지주','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'139480','code'=>'139480','name'=>'이마트','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'144600','code'=>'144600','name'=>'KODEX 은선물','market'=>'KR','exchange'=>'ETF','currency'=>'KRW','asset_type'=>'ETF','enabled'=>false],
        ['symbol'=>'145020','code'=>'145020','name'=>'휴젤','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'157500','code'=>'157500','name'=>'TIGER 증권','market'=>'KR','exchange'=>'ETF','currency'=>'KRW','asset_type'=>'ETF','enabled'=>false],
        ['symbol'=>'161390','code'=>'161390','name'=>'한국타이어앤테크놀로지','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'161510','code'=>'161510','name'=>'TIGER 고배당','market'=>'KR','exchange'=>'ETF','currency'=>'KRW','asset_type'=>'ETF','enabled'=>false],
        ['symbol'=>'187660','code'=>'187660','name'=>'현대ADM','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>false],
        ['symbol'=>'196170','code'=>'196170','name'=>'알테오젠','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'207940','code'=>'207940','name'=>'삼성바이오로직스','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'214150','code'=>'214150','name'=>'클래시스','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'214370','code'=>'214370','name'=>'케어젠','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'214450','code'=>'214450','name'=>'파마리서치','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'215200','code'=>'215200','name'=>'메가스터디교육','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'229200','code'=>'229200','name'=>'KODEX 코스닥150','market'=>'KR','exchange'=>'ETF','currency'=>'KRW','asset_type'=>'ETF','enabled'=>true],
        ['symbol'=>'233740','code'=>'233740','name'=>'KODEX 코스닥150레버리지','market'=>'KR','exchange'=>'ETF','currency'=>'KRW','asset_type'=>'ETF','enabled'=>false],
        ['symbol'=>'240810','code'=>'240810','name'=>'원익IPS','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'241560','code'=>'241560','name'=>'두산밥캣','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'247540','code'=>'247540','name'=>'에코프로비엠','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'251270','code'=>'251270','name'=>'넷마블','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'251340','code'=>'251340','name'=>'KODEX 코스닥150선물인버스','market'=>'KR','exchange'=>'ETF','currency'=>'KRW','asset_type'=>'ETF','enabled'=>false],
        ['symbol'=>'252670','code'=>'252670','name'=>'KODEX 200선물인버스2X','market'=>'KR','exchange'=>'ETF','currency'=>'KRW','asset_type'=>'ETF','enabled'=>false],
        ['symbol'=>'253450','code'=>'253450','name'=>'스튜디오드래곤','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'259960','code'=>'259960','name'=>'크래프톤','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'263750','code'=>'263750','name'=>'펄어비스','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'267250','code'=>'267250','name'=>'HD현대','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'267260','code'=>'267260','name'=>'HD현대일렉트릭','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'272210','code'=>'272210','name'=>'한화시스템','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'277810','code'=>'277810','name'=>'레인보우로보틱스','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'278280','code'=>'278280','name'=>'천보','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'282330','code'=>'282330','name'=>'BGF리테일','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'293490','code'=>'293490','name'=>'카카오게임즈','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'298040','code'=>'298040','name'=>'효성중공업','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'298380','code'=>'298380','name'=>'에이비엘바이오','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'302440','code'=>'302440','name'=>'SK바이오사이언스','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'305540','code'=>'305540','name'=>'TIGER 2차전지테마','market'=>'KR','exchange'=>'ETF','currency'=>'KRW','asset_type'=>'ETF','enabled'=>false],
        ['symbol'=>'305720','code'=>'305720','name'=>'KODEX 2차전지산업','market'=>'KR','exchange'=>'ETF','currency'=>'KRW','asset_type'=>'ETF','enabled'=>false],
        ['symbol'=>'307950','code'=>'307950','name'=>'현대오토에버','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'316140','code'=>'316140','name'=>'우리금융지주','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'319400','code'=>'319400','name'=>'현대무벡스','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'323410','code'=>'323410','name'=>'카카오뱅크','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'326030','code'=>'326030','name'=>'SK바이오팜','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'329180','code'=>'329180','name'=>'HD현대중공업','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'336260','code'=>'336260','name'=>'두산퓨얼셀','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'336370','code'=>'336370','name'=>'솔루스첨단소재','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'352820','code'=>'352820','name'=>'하이브','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'360750','code'=>'360750','name'=>'TIGER 미국S&P500','market'=>'KR','exchange'=>'ETF','currency'=>'KRW','asset_type'=>'ETF','enabled'=>false],
        ['symbol'=>'361610','code'=>'361610','name'=>'SK아이이테크놀로지','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'364980','code'=>'364980','name'=>'TIGER KRX2차전지K-뉴딜','market'=>'KR','exchange'=>'ETF','currency'=>'KRW','asset_type'=>'ETF','enabled'=>false],
        ['symbol'=>'373220','code'=>'373220','name'=>'LG에너지솔루션','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'375500','code'=>'375500','name'=>'DL이앤씨','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'377300','code'=>'377300','name'=>'카카오페이','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'379800','code'=>'379800','name'=>'KODEX 미국S&P500TR','market'=>'KR','exchange'=>'ETF','currency'=>'KRW','asset_type'=>'ETF','enabled'=>false],
        ['symbol'=>'379810','code'=>'379810','name'=>'KODEX 미국나스닥100TR','market'=>'KR','exchange'=>'ETF','currency'=>'KRW','asset_type'=>'ETF','enabled'=>false],
        ['symbol'=>'382480','code'=>'382480','name'=>'지아이텍','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'396500','code'=>'396500','name'=>'TIGER Fn반도체TOP10','market'=>'KR','exchange'=>'ETF','currency'=>'KRW','asset_type'=>'ETF','enabled'=>false],
        ['symbol'=>'397030','code'=>'397030','name'=>'에이프릴바이오','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'402340','code'=>'402340','name'=>'SK스퀘어','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'403870','code'=>'403870','name'=>'HPSP','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'411060','code'=>'411060','name'=>'ACE KRX금현물','market'=>'KR','exchange'=>'ETF','currency'=>'KRW','asset_type'=>'ETF','enabled'=>false],
        ['symbol'=>'454910','code'=>'454910','name'=>'두산로보틱스','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'458730','code'=>'458730','name'=>'TIGER 미국배당다우존스','market'=>'KR','exchange'=>'ETF','currency'=>'KRW','asset_type'=>'ETF','enabled'=>false],
        ['symbol'=>'475150','code'=>'475150','name'=>'SK이터닉스','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'489790','code'=>'489790','name'=>'한화비전','market'=>'KR','exchange'=>'KOSPI','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'491000','code'=>'491000','name'=>'리브스메드','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>false],
        ['symbol'=>'494120','code'=>'494120','name'=>'큐리오시스','market'=>'KR','exchange'=>'KOSDAQ','currency'=>'KRW','asset_type'=>'STOCK','enabled'=>false],
    ],

    'us'=>[
        ['symbol'=>'AAPL','code'=>'AAPL','name'=>'Apple','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'ABBV','code'=>'ABBV','name'=>'AbbVie','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'ABNB','code'=>'ABNB','name'=>'Airbnb','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'AMAT','code'=>'AMAT','name'=>'Applied Materials','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'AMD','code'=>'AMD','name'=>'AMD','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'AMZN','code'=>'AMZN','name'=>'Amazon','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'ANET','code'=>'ANET','name'=>'Arista','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'ARKK','code'=>'ARKK','name'=>'ARK ETF','market'=>'US','exchange'=>'AMEX','exchange_name'=>'NYSE ARCA/AMEX','currency'=>'USD','asset_type'=>'ETF','enabled'=>true],
        ['symbol'=>'ARM','code'=>'ARM','name'=>'Arm Holdings','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'ASML','code'=>'ASML','name'=>'ASML','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'AVGO','code'=>'AVGO','name'=>'Broadcom','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'BABA','code'=>'BABA','name'=>'Alibaba','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'BAC','code'=>'BAC','name'=>'Bank of America','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'BIDU','code'=>'BIDU','name'=>'Baidu','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'BLK','code'=>'BLK','name'=>'BlackRock','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'BRK.B','code'=>'BRK.B','name'=>'Berkshire Hathaway','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true], // SIS
        ['symbol'=>'C','code'=>'C','name'=>'Citigroup','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'CAT','code'=>'CAT','name'=>'Caterpillar','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'CMCSA','code'=>'CMCSA','name'=>'Comcast','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'COIN','code'=>'COIN','name'=>'Coinbase','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'COST','code'=>'COST','name'=>'Costco','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'CRWD','code'=>'CRWD','name'=>'CrowdStrike','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'CRWV','code'=>'CRWV','name'=>'CoreWeave','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'CVX','code'=>'CVX','name'=>'Chevron','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'DDOG','code'=>'DDOG','name'=>'Datadog','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'DE','code'=>'DE','name'=>'Deere','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'DELL','code'=>'DELL','name'=>'Dell','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true], // SIS
        ['symbol'=>'DHR','code'=>'DHR','name'=>'Danaher','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'DIA','code'=>'DIA','name'=>'Dow ETF','market'=>'US','exchange'=>'AMEX','exchange_name'=>'NYSE ARCA/AMEX','currency'=>'USD','asset_type'=>'ETF','enabled'=>true],
        ['symbol'=>'DIS','code'=>'DIS','name'=>'Disney','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'DPRO','code'=>'DPRO','name'=>'Draganfly','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true], // SIS
        ['symbol'=>'ETN','code'=>'ETN','name'=>'Eaton','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'FTNT','code'=>'FTNT','name'=>'Fortinet','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'GE','code'=>'GE','name'=>'GE Aerospace','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'GEV','code'=>'GEV','name'=>'GE Vernova','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'GOOGL','code'=>'GOOGL','name'=>'Alphabet','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'GS','code'=>'GS','name'=>'Goldman Sachs','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'HD','code'=>'HD','name'=>'Home Depot','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'HON','code'=>'HON','name'=>'Honeywell','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'HOOD','code'=>'HOOD','name'=>'Robinhood','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'HPE','code'=>'HPE','name'=>'HPE','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'ISRG','code'=>'ISRG','name'=>'Intuitive Surgical','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'IWM','code'=>'IWM','name'=>'Russell2000','market'=>'US','exchange'=>'AMEX','exchange_name'=>'NYSE ARCA/AMEX','currency'=>'USD','asset_type'=>'ETF','enabled'=>true],
        ['symbol'=>'JD','code'=>'JD','name'=>'JD','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'JNJ','code'=>'JNJ','name'=>'Johnson & Johnson','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'JPM','code'=>'JPM','name'=>'JPMorgan','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'KLAC','code'=>'KLAC','name'=>'KLA','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'KO','code'=>'KO','name'=>'Coca-Cola','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'KTOS','code'=>'KTOS','name'=>'Kratos Defense','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true], // SIS
        ['symbol'=>'KWEB','code'=>'KWEB','name'=>'China Tech','market'=>'US','exchange'=>'AMEX','exchange_name'=>'NYSE ARCA/AMEX','currency'=>'USD','asset_type'=>'ETF','enabled'=>true],
        ['symbol'=>'LLY','code'=>'LLY','name'=>'Eli Lilly','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'LRCX','code'=>'LRCX','name'=>'Lam Research','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'MA','code'=>'MA','name'=>'Mastercard','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'MARA','code'=>'MARA','name'=>'Marathon','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'MCD','code'=>'MCD','name'=>'McDonalds','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'MDB','code'=>'MDB','name'=>'MongoDB','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'META','code'=>'META','name'=>'Meta','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'MPWR','code'=>'MPWR','name'=>'Monolithic Power','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'MRK','code'=>'MRK','name'=>'Merck','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'MRVL','code'=>'MRVL','name'=>'Marvell','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'MS','code'=>'MS','name'=>'Morgan Stanley','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true], // SIS
        ['symbol'=>'MSFT','code'=>'MSFT','name'=>'Microsoft','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'MU','code'=>'MU','name'=>'Micron','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'NET','code'=>'NET','name'=>'Cloudflare','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'NKE','code'=>'NKE','name'=>'Nike','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'NVDA','code'=>'NVDA','name'=>'NVIDIA','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'NXPI','code'=>'NXPI','name'=>'NXP','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'OKTA','code'=>'OKTA','name'=>'Okta','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'ON','code'=>'ON','name'=>'ON Semi','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'ORCL','code'=>'ORCL','name'=>'Oracle','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'PANW','code'=>'PANW','name'=>'Palo Alto','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'PDD','code'=>'PDD','name'=>'PDD','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'PEP','code'=>'PEP','name'=>'Pepsi','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'PFE','code'=>'PFE','name'=>'Pfizer','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'PG','code'=>'PG','name'=>'P&G','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'PH','code'=>'PH','name'=>'Parker','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'PLTR','code'=>'PLTR','name'=>'Palantir','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'PWR','code'=>'PWR','name'=>'Quanta','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'QCOM','code'=>'QCOM','name'=>'Qualcomm','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'QQQ','code'=>'QQQ','name'=>'NASDAQ ETF','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'ETF','enabled'=>true],
        ['symbol'=>'RBLX','code'=>'RBLX','name'=>'Roblox','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'RCAT','code'=>'RCAT','name'=>'Red Cat Holdings','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true], // SIS
        ['symbol'=>'RIOT','code'=>'RIOT','name'=>'Riot','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'RTX','code'=>'RTX','name'=>'RTX','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'SBUX','code'=>'SBUX','name'=>'Starbucks','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'SCHW','code'=>'SCHW','name'=>'Schwab','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'SHOP','code'=>'SHOP','name'=>'Shopify','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'SLB','code'=>'SLB','name'=>'Schlumberger','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'SMCI','code'=>'SMCI','name'=>'Supermicro','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'SMH','code'=>'SMH','name'=>'Semiconductor ETF','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'ETF','enabled'=>true],
        ['symbol'=>'SNDK','code'=>'SNDK','name'=>'Sandisk','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'SNOW','code'=>'SNOW','name'=>'Snowflake','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'SOXL','code'=>'SOXL','name'=>'3X Semiconductor','market'=>'US','exchange'=>'AMEX','exchange_name'=>'NYSE ARCA/AMEX','currency'=>'USD','asset_type'=>'ETF','enabled'=>true],
        ['symbol'=>'SOXX','code'=>'SOXX','name'=>'iShares Semi','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'ETF','enabled'=>true],
        ['symbol'=>'SPY','code'=>'SPY','name'=>'S&P500 ETF','market'=>'US','exchange'=>'AMEX','exchange_name'=>'NYSE ARCA/AMEX','currency'=>'USD','asset_type'=>'ETF','enabled'=>true],
        ['symbol'=>'TMO','code'=>'TMO','name'=>'Thermo Fisher','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'TQQQ','code'=>'TQQQ','name'=>'3X Nasdaq','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'ETF','enabled'=>true],
        ['symbol'=>'TSM','code'=>'TSM','name'=>'TSMC (ADR)','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'TSLA','code'=>'TSLA','name'=>'Tesla','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'TT','code'=>'TT','name'=>'Trane','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'UBER','code'=>'UBER','name'=>'Uber','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'UNH','code'=>'UNH','name'=>'UnitedHealth','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'V','code'=>'V','name'=>'Visa','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'VOO','code'=>'VOO','name'=>'Vanguard S&P500','market'=>'US','exchange'=>'AMEX','exchange_name'=>'NYSE ARCA/AMEX','currency'=>'USD','asset_type'=>'ETF','enabled'=>true],
        ['symbol'=>'VRT','code'=>'VRT','name'=>'Vertiv','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'VRTX','code'=>'VRTX','name'=>'Vertex','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'VST','code'=>'VST','name'=>'Vistra','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'VTI','code'=>'VTI','name'=>'Total Market','market'=>'US','exchange'=>'AMEX','exchange_name'=>'NYSE ARCA/AMEX','currency'=>'USD','asset_type'=>'ETF','enabled'=>true],
        ['symbol'=>'WFC','code'=>'WFC','name'=>'Wells Fargo','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'WMT','code'=>'WMT','name'=>'Walmart','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'XLE','code'=>'XLE','name'=>'Energy ETF','market'=>'US','exchange'=>'AMEX','exchange_name'=>'NYSE ARCA/AMEX','currency'=>'USD','asset_type'=>'ETF','enabled'=>true],
        ['symbol'=>'XLF','code'=>'XLF','name'=>'Finance ETF','market'=>'US','exchange'=>'AMEX','exchange_name'=>'NYSE ARCA/AMEX','currency'=>'USD','asset_type'=>'ETF','enabled'=>true],
        ['symbol'=>'XLK','code'=>'XLK','name'=>'Tech ETF','market'=>'US','exchange'=>'AMEX','exchange_name'=>'NYSE ARCA/AMEX','currency'=>'USD','asset_type'=>'ETF','enabled'=>true],
        ['symbol'=>'XOM','code'=>'XOM','name'=>'Exxon','market'=>'US','exchange'=>'NYSE','exchange_name'=>'NYSE','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'ZS','code'=>'ZS','name'=>'Zscaler','market'=>'US','exchange'=>'NASD','exchange_name'=>'NASDAQ','currency'=>'USD','asset_type'=>'STOCK','enabled'=>true],
    ],

    'jp'=>[
        ['symbol'=>'1605','code'=>'1605','name'=>'INPEX','name_en'=>'INPEX','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'258A','code'=>'258A','name'=>'SMT SELECTED J-REIT ACTIVE','name_en'=>'SMT Selected J-REIT Active','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'ETF','enabled'=>true],
        ['symbol'=>'285A','code'=>'285A','name'=>'키옥시아홀딩스','name_en'=>'Kioxia Holdings','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'2914','code'=>'2914','name'=>'일본담배산업','name_en'=>'Japan Tobacco','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'4062','code'=>'4062','name'=>'이비덴','name_en'=>'Ibiden','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'4063','code'=>'4063','name'=>'신에츠화학공업','name_en'=>'Shin-Etsu Chemical','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'4502','code'=>'4502','name'=>'다케다약품공업','name_en'=>'Takeda Pharmaceutical','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'4519','code'=>'4519','name'=>'주가이제약','name_en'=>'Chugai Pharmaceutical','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'4568','code'=>'4568','name'=>'다이이찌산쿄','name_en'=>'Daiichi Sankyo','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'5108','code'=>'5108','name'=>'브리지스톤','name_en'=>'Bridgestone','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'5401','code'=>'5401','name'=>'일본제철','name_en'=>'Nippon Steel','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'5801','code'=>'5801','name'=>'후루카와전기','name_en'=>'Furukawa Electric','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'5803','code'=>'5803','name'=>'후지쿠라','name_en'=>'Fujikura','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'6098','code'=>'6098','name'=>'리크루트홀딩스','name_en'=>'Recruit Holdings','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'6301','code'=>'6301','name'=>'고마쓰','name_en'=>'Komatsu','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'6367','code'=>'6367','name'=>'다이킨공업','name_en'=>'Daikin Industries','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'6501','code'=>'6501','name'=>'히타치제작소','name_en'=>'Hitachi','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'6525','code'=>'6525','name'=>'코쿠사이일렉트릭','name_en'=>'Kokusai Electric','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'6594','code'=>'6594','name'=>'니덱','name_en'=>'Nidec','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'6752','code'=>'6752','name'=>'파나소닉홀딩스','name_en'=>'Panasonic Holdings','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'6758','code'=>'6758','name'=>'소니그룹','name_en'=>'Sony Group','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'6857','code'=>'6857','name'=>'어드반테스트','name_en'=>'Advantest','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'6861','code'=>'6861','name'=>'키엔스','name_en'=>'Keyence','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'6902','code'=>'6902','name'=>'덴소','name_en'=>'Denso','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'6954','code'=>'6954','name'=>'화낙','name_en'=>'Fanuc','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'6971','code'=>'6971','name'=>'교세라','name_en'=>'Kyocera','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'6976','code'=>'6976','name'=>'다이요유덴','name_en'=>'Taiyo Yuden','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'6981','code'=>'6981','name'=>'무라타제작소','name_en'=>'Murata Manufacturing','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'7011','code'=>'7011','name'=>'미쓰비시중공업','name_en'=>'Mitsubishi Heavy Industries','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'7012','code'=>'7012','name'=>'가와사키중공업','name_en'=>'Kawasaki Heavy Industries','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'7013','code'=>'7013','name'=>'IHI','name_en'=>'IHI','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'7203','code'=>'7203','name'=>'도요타자동차','name_en'=>'Toyota Motor','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'7267','code'=>'7267','name'=>'혼다자동차','name_en'=>'Honda Motor','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'7741','code'=>'7741','name'=>'호야','name_en'=>'Hoya','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'7974','code'=>'7974','name'=>'닌텐도','name_en'=>'Nintendo','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'8001','code'=>'8001','name'=>'이토추상사','name_en'=>'Itochu','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'8002','code'=>'8002','name'=>'마루베니','name_en'=>'Marubeni','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'8031','code'=>'8031','name'=>'미쓰이물산','name_en'=>'Mitsui & Co.','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'8035','code'=>'8035','name'=>'도쿄일렉트론','name_en'=>'Tokyo Electron','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'8058','code'=>'8058','name'=>'미쓰비시상사','name_en'=>'Mitsubishi Corporation','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'8306','code'=>'8306','name'=>'미쓰비시UFJ파이낸셜그룹','name_en'=>'Mitsubishi UFJ Financial Group','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'8316','code'=>'8316','name'=>'스미토모미쓰이파이낸셜그룹','name_en'=>'Sumitomo Mitsui Financial Group','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'8411','code'=>'8411','name'=>'미즈호파이낸셜그룹','name_en'=>'Mizuho Financial Group','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'8766','code'=>'8766','name'=>'도쿄해상홀딩스','name_en'=>'Tokio Marine Holdings','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'8801','code'=>'8801','name'=>'미쓰이부동산','name_en'=>'Mitsui Fudosan','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'8802','code'=>'8802','name'=>'미쓰비시지쇼','name_en'=>'Mitsubishi Estate','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'9020','code'=>'9020','name'=>'동일본여객철도','name_en'=>'East Japan Railway','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'9022','code'=>'9022','name'=>'도카이여객철도','name_en'=>'Central Japan Railway','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'9432','code'=>'9432','name'=>'NTT','name_en'=>'NTT','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'9433','code'=>'9433','name'=>'KDDI','name_en'=>'KDDI','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'9983','code'=>'9983','name'=>'패스트리테일링','name_en'=>'Fast Retailing','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
        ['symbol'=>'9984','code'=>'9984','name'=>'소프트뱅크그룹','name_en'=>'SoftBank Group','market'=>'JP','exchange'=>'TKSE','exchange_name'=>'Tokyo Stock Exchange','currency'=>'JPY','asset_type'=>'STOCK','enabled'=>true],
    ],
];